[project]
name = "ezetl"
version = "0.1.0"
description = "Easy ETL"
readme = "README.md"
authors = [
    { name = "mohamad-tohidi", email = "the.mohammad.tohidi@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "janus>=2.0.0",
    "tqdm>=4.67.1",
]

[build-system]
requires = ["uv_build>=0.9.8,<0.10.0"]
build-backend = "uv_build"
